"""Recovered Pearlhash per-frame XOR keystreams.

Source: `C:/Source/pearl-investigation/wave16-domination/51_pearlhash_cipher_re.md` §2.3.

Each entry maps a frame index N (0-based; resets to 0 on each TCP reconnect)
to its 48-byte XOR keystream. The keystream cycles for the body length of the
frame: frame body = `XOR(plaintext, KEY_msg[N] * (body_len // 48 + 1))[:body_len]`.

Recovery method: known-plaintext attack against JSON-RPC templates harvested
from process memory dumps; verified bit-exact across multiple independent
captures (cap_long.pcap on production wallet + cap_verify.pcap on decoy wallet).
The keystreams are connection-independent — the wallet identity does NOT affect
the keystream.

What's KNOWN:
  KEY_MSG[0]    : login frame (`{"id":0,"method":"login",...}`)
  KEY_MSG[1..15]: report_info keepalives (`{"id":N,"method":"report_info",...}`)

What's UNKNOWN (recovery requires 1 paired capture each):
  KEY_MSG[16+]  : submit frames (`{"id":N,"method":"submit",...}`) — see
                  PEARLHASH_README.md §"How to capture a submit keystream".
  KEY_SRV_*     : server->client frames (login resp A/B/C, set_difficulty,
                  new_job, share_result) — completely unknown, see memo 51 §6.

KEY_DERIVATION is deterministic: the binary calls `srand(0)` at TCP connect and
emits `htonl(rand_N)` as the first 4 bytes of each C->S frame. The per-frame
48-byte XOR table itself is generated by an opaque algorithm inside the packed
pearl-miner v2 binary; static analysis hasn't recovered the function yet. Once
recovered (via Ghidra; memo 51 §4.2, ETA 3-5 days), this table would be
replaced by a generator. For now we ship the lookup table.
"""

from __future__ import annotations

# C->S keystreams, indexed by frame number (0-based).
# Frame N=0 is always the login; N=1..15 are report_info keepalives.
KEY_MSG_HEX: dict[int, str] = {
    0:  "055fcdb9f6c36ca431d519566ccad9d5"
        "b9a7cdf9aaa1c1aa93a18c00e5006799"
        "3134cdb9f90595699e99673305b9cd4f",
    1:  "2474de1abe3ae814b67cdaa2e8d2ee82"
        "67b43e3ab5d06ab52c30978278ddc616"
        "2a518c674a2482a0ef167820756780ac",
    2:  "330d3f07146de9e7c76b979fe9016e27"
        "53f9e36358b57f58e9473d55310b69a3"
        "473bd15377339773b1a37dae7e53cd73",
    3:  "6101a53d3d09b381f5efcdb0b3087d15"
        "2a295dbddf452ddf35e62cbdcb3f73c9"
        "9558e52ae56129b104c9ef82922a7d01",
    4:  "67e5e71f7c774e4949e72f954e7d5603"
        "3cedc7c7166d9f16b3b81dc72d925143"
        "87f1a13c5767b3e1d4437ac5503cf392",
    5:  "c963012115ed7fd8c315a1d87fcc97b1"
        "57b1ed8d5aefb15adb8d0f20b7fbfff9"
        "f1fcfd57a1c961f9f0f9f1b5ba577572",
    6:  "9c3c2e964b884e2dc4d406df4ebbba9e"
        "676e6e2a6f02c66fc0cd59b61a714a26"
        "4edd9467d69ca2b899262e64db672436",
    7:  "9c1068b4d86661f1601eb4ef61d8600c"
        "1dbc1044cae654ca4a84dff09a9aecb0"
        "5cc4d81d549c788849b01e86a31dd8f2",
    8:  "c5792ba784eb1c241ba3c7a11c4d7883"
        "9685e3932a3d672a67d4b882abc929a3"
        "477b5196bfc5bbf36ba3c015c196294a",
    9:  "0569e3e38da9963439a5d3889695782346199b0b1533831527404f248300cd33"
        "636699461b05d3cd3433ceaf0a469b45",
    10: "cafa2e26246e5754f6bef68d57874866"
        "c50ab6966f2a1e6f9e113b7382a0bae6"
        "ce2c74c5eeca425a85e6f6f1c2c5e41a",
    11: "0347bda500e758fd8fb35510580591c1"
        "f9f3fd0d5d55d55d97079953fb55aba9"
        "550055f95503cd01ffa952e4b6f903d1",
    12: "489e42ee31a0e3c4aa406e0ee3815d82"
        "91ec5686ff36deff101d037fa0baf2c6"
        "8ed4e491264842aa7dc66159f9915835",
    13: "57d3e905969b7739bfa5356877720a69"
        "f8ebbdc1f9af6df9437ff73515e3fbe9"
        "d5f0f5f8e55771e1cce9c62ddff8ef41",
    14: "83a1252df67fb26f3591ed36b2ecec31"
        "6add991dcb5d9dcb090ff0b4156ce389"
        "15a7c56a4583d94df689ba54b36a5509",
    15: "2486524a3e4435a9a8b8dab8355e40ba"
        "0ec03e3a52d49a5236b63e84605d4616"
        "2ad18c0e022416a07216fe7ff00ece8c",
}


def _materialize() -> dict[int, bytes]:
    out = {}
    for idx, hexstr in KEY_MSG_HEX.items():
        kb = bytes.fromhex(hexstr)
        if len(kb) != 48:
            raise ValueError(
                f"KEY_MSG[{idx}] is {len(kb)} bytes, expected 48 (cipher invariant)"
            )
        out[idx] = kb
    return out


# 48-byte keystreams, ready for XOR.
KEY_MSG: dict[int, bytes] = _materialize()


# Counter (first 4 bytes of every C->S frame, htonl(rand_N) from srand(0)) ->
# frame index. Derived from the glibc rand sequence — see
# pearlhash_rand.glibc_rand_sequence(16).
# Provided as a constant lookup because both ends use it (encode + decode).
COUNTER_TO_FRAME_INDEX: dict[int, int] = {
    0x6B8B4567: 0,
    0x327B23C6: 1,
    0x643C9869: 2,
    0x66334873: 3,
    0x74B0DC51: 4,
    0x19495CFF: 5,
    0x2AE8944A: 6,
    0x625558EC: 7,
    0x238E1F29: 8,
    0x46E87CCD: 9,
    0x3D1B58BA: 10,
    0x507ED7AB: 11,
    0x2EB141F2: 12,
    0x41B71EFB: 13,
    0x79E2A9E3: 14,
    0x7545E146: 15,
}


# Highest frame index for which we have a C->S keystream. Frames beyond this
# require recapture (memo 51 §4.1 path A, "1 paired capture per new index").
MAX_KNOWN_FRAME_INDEX: int = max(KEY_MSG)


# Reserved for future submit-frame keystreams. Empty until at least one
# pearl-miner v2 submit frame has been captured + memory-dumped + reversed.
# See PEARLHASH_README.md §"How to capture a submit keystream".
SUBMIT_KEY_MSG: dict[int, bytes] = {}
