# This populates the csrc/gemm/instantiations directory, and is run by setup.py.
# To control which kernels are actually compiled at build time, edit compiled_kernels.cfg.
import itertools
import os
from pathlib import Path

from pearl_gemm_build_utils.kernel_configs import (
    MatmulKernelConfig,
    NoisingAKernelConfig,
    NoisingBKernelConfig,
)

filename_type_to_cutlass_type = {
    "fp16": "cutlass::half_t",
    "int32": "int",
    "int": "int",
    "bf16": "cutlass::bfloat16_t",
}


def noisy_gemm_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_gemm_host.h"

    /* Autogenerated -- see generate_instantiations.py
	    * run_pearl_gemm_<ElementOut, R, bM, bN, bK, kStages, cM, cN, SkipReduction, SkipDenoising, ProofOnly, SkipProofCheck, EnableDebug, EnableXqJournal, EnableCanonicalTranscript, EnableDummyReduction, EnableRawRing2x64, EnableRawXorOnly2x64, EnableRawStoreOnly2x64, EnableRawDeferredRing2x64, EnableRawGlobalSink2x64, EnableNative2x64Ring, EnableNativeGlobalJournalFill>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def noising_A_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingA_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_A_<ElementDenoise_AxEBL, R, bM_noising_A, bK_noising_A, kStages, ComputeDenoiseIntermediates>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def noising_B_prelude() -> str:
    prelude = """#include <cutlass/numeric_types.h>

    #include "gemm/pearl_api_params.h"
    #include "gemm/pearl_gemm_launch_template.h"
    #include "gemm/pearl_noisingB_host.h"

    /* Autogenerated -- see generate_instantiations.py
    * run_pearl_noising_B_<ElementDenoise_EARxBpEB, R, bN_noising_B, bK_noising_B, kStages, ComputeDenoiseIntermediates>(PearlAPIParams& params, cudaStream_t stream);
    */

    """
    return prelude


def to_str(b: bool):
    return str(b).lower()


def env_flag(name: str) -> bool:
    return os.getenv(name, "").casefold() in ("1", "true", "t", "yes", "y")


def gemm_decl(
    config: MatmulKernelConfig,
    out_type: str,
    SkipReduction: bool,
    SkipDenoising: bool,
    ProofOnly: bool,
    SkipProofCheck: bool,
    EnableDebug: bool,
    EnableXqJournal: bool,
    EnableCanonicalTranscript: bool,
    EnableDummyReduction: bool,
    EnableRawRing2x64: bool,
    EnableRawXorOnly2x64: bool,
    EnableRawStoreOnly2x64: bool,
    EnableRawDeferredRing2x64: bool,
    EnableRawGlobalSink2x64: bool,
    EnableNative2x64Ring: bool,
    EnableNativeGlobalJournalFill: bool,
) -> str:
    out_type = filename_type_to_cutlass_type[out_type]
    condition = "#if "
    if SkipReduction:
        condition += "!defined(DISABLE_SKIP_REDUCTION) && "
    if SkipDenoising:
        condition += "!defined(DISABLE_SKIP_DENOISING) && "
    if ProofOnly:
        condition += "!defined(DISABLE_PROOF_ONLY) && "
    else:
        condition += "!defined(DISABLE_NON_PROOF_ONLY) && "
    if EnableDebug:
        condition += "!defined(DISABLE_DEBUG_MODE) && "
    if EnableXqJournal:
        condition += "!defined(DISABLE_XQ_JOURNAL) && "
    if EnableCanonicalTranscript:
        condition += "!defined(DISABLE_CANONICAL_TRANSCRIPT) && "
    condition = condition[:-4]
    decl = ""
    if condition:
        decl = condition + "\n"
    decl += f"\ttemplate void run_pearl_gemm_<{out_type}, {config.R}, {config.tile_size_m}, {config.tile_size_n}, {config.tile_size_k}, {config.pipeline_stages}, {config.cM}, {config.cN}, {to_str(SkipReduction)}, {to_str(SkipDenoising)}, {to_str(ProofOnly)}, {to_str(SkipProofCheck)}, {to_str(EnableDebug)}, {to_str(EnableXqJournal)}, {to_str(EnableCanonicalTranscript)}, {to_str(EnableDummyReduction)}, {to_str(EnableRawRing2x64)}, {to_str(EnableRawXorOnly2x64)}, {to_str(EnableRawStoreOnly2x64)}, {to_str(EnableRawDeferredRing2x64)}, {to_str(EnableRawGlobalSink2x64)}, {to_str(EnableNative2x64Ring)}, {to_str(EnableNativeGlobalJournalFill)}>(PearlAPIParams&, cudaStream_t);\n"
    if condition:
        decl += "#endif\n"
    return decl


def noising_A_decl(config: NoisingAKernelConfig) -> str:
    AxEBL_type = filename_type_to_cutlass_type[config.AxEBL_type]
    decl = ""
    for compute_denoise in (True, False):
        if compute_denoise:
            decl += "#if !defined(DISABLE_DENOISE_INTERMEDIATES)\n"
        decl += f"\ttemplate void run_pearl_noising_A_<{AxEBL_type}, {config.R}, {config.tile_size_m}, {config.tile_size_k}, {config.pipeline_stages}, {to_str(compute_denoise)}>(PearlAPIParams&, cudaStream_t);\n"
        if compute_denoise:
            decl += "#endif\n"
    return decl


def noising_B_decl(config: NoisingBKernelConfig) -> str:
    EARxBpEB_type = filename_type_to_cutlass_type[config.EARxBpEB_type]

    decl = ""
    for compute_denoise in (True, False):
        if compute_denoise:
            decl += "#if !defined(DISABLE_DENOISE_INTERMEDIATES)\n"
        decl += f"\ttemplate void run_pearl_noising_B_< {EARxBpEB_type}, {config.R}, {config.tile_size_n}, {config.tile_size_k}, {config.pipeline_stages}, {to_str(compute_denoise)}>(PearlAPIParams&, cudaStream_t);\n"
        if compute_denoise:
            decl += "#endif\n"
    return decl


def generate_instantiations(
    matmul_kernels: list[MatmulKernelConfig],
    noising_a_kernels: list[NoisingAKernelConfig],
    noising_b_kernels: list[NoisingBKernelConfig],
    output_dir: Path,
):
    SKIP_REDUCTION = [False, True]
    SKIP_DENOISING = [False, True]
    PROOF_ONLY = [False, True]
    SKIP_PROOF_CHECK = [False, True]
    ENABLE_DEBUG = [False, True]
    ENABLE_CANONICAL_TRANSCRIPT = [False, True]
    ENABLE_DUMMY_REDUCTION = [False, True]
    ENABLE_RAW_RING_2X64 = [False, True]
    ENABLE_RAW_XOR_ONLY_2X64 = [False, True]
    ENABLE_RAW_STORE_ONLY_2X64 = [False, True]
    ENABLE_RAW_DEFERRED_RING_2X64 = [False, True]
    ENABLE_RAW_GLOBAL_SINK_2X64 = [False, True]
    ENABLE_NATIVE_2X64_RING = [False, True]
    ENABLE_NATIVE_GLOBAL_JOURNAL_FILL = [False, True]
    if env_flag("PEARL_GEMM_P1K104_DUMMY_ONLY"):
        SKIP_REDUCTION = [False, True]
        SKIP_DENOISING = [True]
        PROOF_ONLY = [True]
        SKIP_PROOF_CHECK = [False, True]
        ENABLE_DEBUG = [False]
        # Keep one-hot diagnostic branches instantiated because pearl_gemm_api.cpp
        # still references them from runtime flag branches even when P1K104 only
        # runs the default/dummy reduction cases.
        ENABLE_CANONICAL_TRANSCRIPT = [False, True]
        ENABLE_DUMMY_REDUCTION = [False, True]
        ENABLE_RAW_RING_2X64 = [False, True]
        ENABLE_RAW_XOR_ONLY_2X64 = [False, True]
        ENABLE_RAW_STORE_ONLY_2X64 = [False, True]
        ENABLE_RAW_DEFERRED_RING_2X64 = [False, True]
        ENABLE_RAW_GLOBAL_SINK_2X64 = [False, True]
        ENABLE_NATIVE_2X64_RING = [False, True]
        ENABLE_NATIVE_GLOBAL_JOURNAL_FILL = [False, True]
    if env_flag("PEARL_GEMM_P1K138_OUTPUT_STORE_ONLY"):
        SKIP_REDUCTION = [False, True]
        SKIP_DENOISING = [False, True]
        PROOF_ONLY = [False, True]
        SKIP_PROOF_CHECK = [False, True]
        ENABLE_DEBUG = [False]
        # pearl_gemm_api.cpp still has dynamic branches for proof-only
        # diagnostics, so the extension must export those referenced template
        # symbols even when this P1K-138 run only calls a narrow benchmark
        # matrix. noisy_gemm also references skip-reduction/no-skip-denoising.
        ENABLE_CANONICAL_TRANSCRIPT = [False, True]
        ENABLE_DUMMY_REDUCTION = [False, True]
        ENABLE_RAW_RING_2X64 = [False, True]
        ENABLE_RAW_XOR_ONLY_2X64 = [False, True]
        ENABLE_RAW_STORE_ONLY_2X64 = [False, True]
        ENABLE_RAW_DEFERRED_RING_2X64 = [False, True]
        ENABLE_RAW_GLOBAL_SINK_2X64 = [False, True]
        ENABLE_NATIVE_2X64_RING = [False, True]
        ENABLE_NATIVE_GLOBAL_JOURNAL_FILL = [False, True]
    OUTPUT_TYPES = ["bf16"]
    # create instantiations directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)

    # clean out directory
    files = output_dir.glob("*.cu")
    for f in files:
        os.remove(f)

    # populate directory
    for config in matmul_kernels:
        for out_type in OUTPUT_TYPES:
            output_filename = f"gemm_R{config.R}_{out_type}_{config.tile_size_m}x{config.tile_size_n}x{config.tile_size_k}_{config.pipeline_stages}stages_cluster{config.cM}x{config.cN}.cu"
            output_file = Path(output_dir) / output_filename
            with open(output_file, "w") as fh:
                fh.write(f"#if !defined(DISABLE_R{config.R})")
                fh.write("\n" + noisy_gemm_prelude())
                for (
                    SkipReduction,
                    SkipDenoising,
                    ProofOnly,
                    SkipProofCheck,
                    EnableDebug,
                    EnableXqJournal,
                    EnableCanonicalTranscript,
                    EnableDummyReduction,
                    EnableRawRing2x64,
                    EnableRawXorOnly2x64,
                    EnableRawStoreOnly2x64,
                    EnableRawDeferredRing2x64,
                    EnableRawGlobalSink2x64,
                    EnableNative2x64Ring,
                    EnableNativeGlobalJournalFill,
                ) in itertools.product(
                    SKIP_REDUCTION,
                    SKIP_DENOISING,
                    PROOF_ONLY,
                    SKIP_PROOF_CHECK,
                    ENABLE_DEBUG,
                    (False, True),
                    ENABLE_CANONICAL_TRANSCRIPT,
                    ENABLE_DUMMY_REDUCTION,
                    ENABLE_RAW_RING_2X64,
                    ENABLE_RAW_XOR_ONLY_2X64,
                    ENABLE_RAW_STORE_ONLY_2X64,
                    ENABLE_RAW_DEFERRED_RING_2X64,
                    ENABLE_RAW_GLOBAL_SINK_2X64,
                    ENABLE_NATIVE_2X64_RING,
                    ENABLE_NATIVE_GLOBAL_JOURNAL_FILL,
                ):
                    if ProofOnly and not SkipDenoising:
                        continue
                    if SkipProofCheck and (SkipReduction or not ProofOnly):
                        continue
                    if EnableXqJournal and (SkipReduction or not ProofOnly):
                        continue
                    if EnableCanonicalTranscript and (
                        SkipReduction or not ProofOnly or EnableXqJournal
                    ):
                        continue
                    if EnableDummyReduction and (
                        SkipReduction
                        or not ProofOnly
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                    ):
                        continue
                    if EnableRawRing2x64 and (
                        config.R != 128
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableRawXorOnly2x64 and (
                        config.R != 128
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableRawStoreOnly2x64 and (
                        config.R != 128
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableRawDeferredRing2x64 and (
                        config.R != 128
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableRawGlobalSink2x64 and (
                        config.R != 128
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableNative2x64Ring and (
                        config.R != 128
                        or config.tile_size_m != 128
                        or config.tile_size_n not in (64, 128, 256)
                        or config.tile_size_k not in (64, 128)
                        or config.pipeline_stages != 3
                        or config.cM not in (1, 2)
                        or config.cN != 1
                        or SkipReduction
                        or not ProofOnly
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if EnableNativeGlobalJournalFill and (
                        config.R != 128
                        or config.tile_size_m != 128
                        or config.tile_size_n not in (64, 128, 256)
                        or config.tile_size_k not in (64, 128)
                        or config.pipeline_stages != 3
                        or config.cM not in (1, 2)
                        or config.cN != 1
                        or SkipReduction
                        or not ProofOnly
                        or not SkipProofCheck
                        or EnableXqJournal
                        or EnableCanonicalTranscript
                        or EnableDummyReduction
                    ):
                        continue
                    if (
                        int(EnableRawRing2x64)
                        + int(EnableRawXorOnly2x64)
                        + int(EnableRawStoreOnly2x64)
                        + int(EnableRawDeferredRing2x64)
                        + int(EnableRawGlobalSink2x64)
                        + int(EnableNative2x64Ring)
                        + int(EnableNativeGlobalJournalFill)
                        > 1
                    ):
                        continue
                    fh.write(
                        gemm_decl(
                            config,
                            out_type,
                            SkipReduction,
                            SkipDenoising,
                            ProofOnly,
                            SkipProofCheck,
                            EnableDebug,
                            EnableXqJournal,
                            EnableCanonicalTranscript,
                            EnableDummyReduction,
                            EnableRawRing2x64,
                            EnableRawXorOnly2x64,
                            EnableRawStoreOnly2x64,
                            EnableRawDeferredRing2x64,
                            EnableRawGlobalSink2x64,
                            EnableNative2x64Ring,
                            EnableNativeGlobalJournalFill,
                        )
                    )
                fh.write(f"#endif // #if !defined(DISABLE_R{config.R})")

    for config in noising_a_kernels:
        output_filename = f"noisingA_R{config.R}_{config.AxEBL_type}_{config.tile_size_m}x{config.tile_size_k}_{config.pipeline_stages}stages.cu"
        output_file = Path(output_dir) / output_filename
        with open(output_file, "w") as fh:
            fh.write(f"#if !defined(DISABLE_R{config.R})")
            fh.write("\n" + noising_A_prelude())
            fh.write(noising_A_decl(config))
            fh.write("#endif")

    for config in noising_b_kernels:
        output_filename = f"noisingB_R{config.R}_{config.EARxBpEB_type}_{config.tile_size_n}x{config.tile_size_k}_{config.pipeline_stages}stages.cu"
        output_file = Path(output_dir) / output_filename
        with open(output_file, "w") as fh:
            fh.write(f"#if !defined(DISABLE_R{config.R})")
            fh.write("\n" + noising_B_prelude())
            fh.write(noising_B_decl(config))
            fh.write("#endif")
