"""pearl_gemm: CuTe DSL kernels for Pearl's FP8 scheme.

Public surface over caller-owned buffers: the A-side runtime pipeline
(``pre_quant``, ``tensor_hash_plus_stats``, ``noisy_quant``, ``mixed_gemm``),
the B-side per-job preparation (``tensor_hash_plus_stats_b``,
``noise_lines``, ``noisy_quant_b``), the MoE grouped GEMMs
(``grouped_fp8_gemm``, ``grouped_mixed_gemm``), and the persistent
per-process PoW hit signal (``HitSignal``).
"""

from .api import (
    fp16_commit,
    fp16_gemm,
    fp16_miner,
    fp16_noise_lines,
    fp16_noisy_quant,
    fp16_pipeline,
    fp16_policy,
    fp16_search,
)
from .api import (
    LABEL_E1,
    LABEL_E2,
    LABEL_F1,
    LABEL_F2,
    GroupedFp8GemmConfig,
    GroupedMixedGemmConfig,
    Hit,
    HitRecordLayout,
    HitSignal,
    HitSignalConfig,
    HitSignalPoisonedError,
    MixedGemmConfig,
    NoiseLoadMode,
    NoisyQuantBConfig,
    NoisyQuantConfig,
    PreQuantConfig,
    TensorHashConfig,
    default_mixed_gemm_config,
    default_noisy_quant_config,
    get_tensor_hash_plus_stats_config,
    grouped_fp8_gemm,
    grouped_fp8_gemm_scale_shapes,
    grouped_mixed_gemm,
    mixed_gemm,
    noise_lines,
    noisy_quant,
    noisy_quant_b,
    pack_noise_factor,
    pre_quant,
    pre_quant_output_shapes,
    supports_grouped_mixed_gemm,
    supports_lottery_family,
    tensor_hash,
    tensor_hash_plus_stats,
    tensor_hash_plus_stats_b,
    tensor_hash_plus_stats_record_is_legal,
    tensor_hash_scratchpad_bytes,
    tensor_hash_workspace_bytes,
    validate_mixed_gemm_config,
    validate_noisy_quant_config,
)
from .protocol_constants import (
    BLOCK_SCALE_GROUP,
    NOISE_TARGET_NORM,
    PACKED_NOISE_K,
    PEEL_COLS,
    QUANT_MAX,
    R,
)

__all__ = [
    "fp16_commit",
    "fp16_gemm",
    "fp16_miner",
    "fp16_noise_lines",
    "fp16_noisy_quant",
    "fp16_pipeline",
    "fp16_policy",
    "fp16_search",
    "BLOCK_SCALE_GROUP",
    "GroupedFp8GemmConfig",
    "GroupedMixedGemmConfig",
    "Hit",
    "HitRecordLayout",
    "HitSignal",
    "HitSignalConfig",
    "HitSignalPoisonedError",
    "LABEL_E1",
    "LABEL_E2",
    "LABEL_F1",
    "LABEL_F2",
    "MixedGemmConfig",
    "NOISE_TARGET_NORM",
    "PACKED_NOISE_K",
    "PEEL_COLS",
    "NoiseLoadMode",
    "NoisyQuantBConfig",
    "NoisyQuantConfig",
    "PreQuantConfig",
    "QUANT_MAX",
    "R",
    "TensorHashConfig",
    "default_mixed_gemm_config",
    "default_noisy_quant_config",
    "get_tensor_hash_plus_stats_config",
    "grouped_fp8_gemm",
    "grouped_fp8_gemm_scale_shapes",
    "grouped_mixed_gemm",
    "mixed_gemm",
    "noise_lines",
    "noisy_quant",
    "noisy_quant_b",
    "pack_noise_factor",
    "pre_quant",
    "pre_quant_output_shapes",
    "supports_grouped_mixed_gemm",
    "supports_lottery_family",
    "tensor_hash",
    "tensor_hash_plus_stats",
    "tensor_hash_plus_stats_b",
    "tensor_hash_plus_stats_record_is_legal",
    "tensor_hash_scratchpad_bytes",
    "tensor_hash_workspace_bytes",
    "validate_mixed_gemm_config",
    "validate_noisy_quant_config",
]
