"""pearl_gemm: CuTe DSL kernels for Pearl's FP8 scheme.

Public surface over caller-owned buffers: the A-side runtime pipeline
(``pre_quant``, ``tensor_hash_plus_stats``, ``noisy_quant``, ``mixed_gemm``),
the B-side per-job preparation (``tensor_hash_plus_stats_b``,
``noise_lines``, ``noisy_quant_b``), and the persistent per-process PoW hit
signal (``HitSignal``).
"""

from .api import (
    LABEL_E1,
    LABEL_E2,
    LABEL_F1,
    LABEL_F2,
    Hit,
    HitRecordLayout,
    HitSignal,
    HitSignalConfig,
    HitSignalPoisonedError,
    MixedGemmConfig,
    NoiseLoadMode,
    NoisyQuantBConfig,
    NoisyQuantConfig,
    PreQuantConfig,
    TensorHashConfig,
    b_peel_for_a,
    get_tensor_hash_plus_stats_config,
    mixed_gemm,
    noise_lines,
    noisy_quant,
    noisy_quant_b,
    pack_noise_factor,
    pre_quant,
    pre_quant_output_shapes,
    tensor_hash,
    tensor_hash_plus_stats,
    tensor_hash_plus_stats_b,
    tensor_hash_plus_stats_record_is_legal,
    tensor_hash_scratchpad_bytes,
    tensor_hash_workspace_bytes,
    validate_mixed_gemm_config,
    validate_noisy_quant_config,
)
from .protocol_constants import (
    BLOCK_SCALE_GROUP,
    DELTA,
    NOISE_TARGET_NORM,
    PACKED_NOISE_K,
    PEEL_COLS,
    QUANT_MAX,
    R,
)

__all__ = [
    "BLOCK_SCALE_GROUP",
    "DELTA",
    "Hit",
    "HitRecordLayout",
    "HitSignal",
    "HitSignalConfig",
    "HitSignalPoisonedError",
    "LABEL_E1",
    "LABEL_E2",
    "LABEL_F1",
    "LABEL_F2",
    "MixedGemmConfig",
    "NOISE_TARGET_NORM",
    "PACKED_NOISE_K",
    "PEEL_COLS",
    "NoiseLoadMode",
    "NoisyQuantBConfig",
    "NoisyQuantConfig",
    "PreQuantConfig",
    "QUANT_MAX",
    "R",
    "TensorHashConfig",
    "b_peel_for_a",
    "get_tensor_hash_plus_stats_config",
    "mixed_gemm",
    "noise_lines",
    "noisy_quant",
    "noisy_quant_b",
    "pack_noise_factor",
    "pre_quant",
    "pre_quant_output_shapes",
    "tensor_hash",
    "tensor_hash_plus_stats",
    "tensor_hash_plus_stats_b",
    "tensor_hash_plus_stats_record_is_legal",
    "tensor_hash_scratchpad_bytes",
    "tensor_hash_workspace_bytes",
    "validate_mixed_gemm_config",
    "validate_noisy_quant_config",
]
