//! Embedded FP8 ZK verifier cache ([`crate::api::fp8::zk::Fp8VerifierCache`] wire bytes).
//!
//! Generated by the `build_cache` binary from the canonical statement into
//! `fp8_cache.bin` (a build artifact, gitignored; `task build:zk-cache`
//! generates it on a fresh checkout). Verification resolves setups from this
//! cache alone and never compiles them on demand. Regenerate with
//! `cargo run --release --no-default-features --bin build_cache src/api/fp8/fp8_cache.bin`,
//! which rewrites the committed `lut_caps.bin` in the same pass (the cached
//! circuits bake the caps, so the two files move together).

/// The embedded cache binary data (only when the `embedded_cache` feature is enabled).
#[cfg(feature = "embedded_cache")]
pub const CACHE_DATA: &[u8] = include_bytes!("fp8_cache.bin");

/// Empty cache when the `embedded_cache` feature is disabled.
#[cfg(not(feature = "embedded_cache"))]
pub const CACHE_DATA: &[u8] = &[];
