//! The LUT setup commitment, loaded from the committed `lut_caps.bin`.
//!
//! The sixteen LUT tables are committed into a single batched
//! Merkle tree whose cap the wrapper circuits bake (`crate::circuit::fp8::luts`).
//! The flat column list — and hence the cap — is job-independent
//! ([`Fp8System::preprocessed_data`](crate::circuit::fp8::driver::Fp8System::preprocessed_data)),
//! so the cap is a pure function of the tables. [`committed_lut_cap`] only
//! parses the embedded file — the verifier side never builds a LUT oracle.
//!
//! The file is generated by the `build_cache` binary, which derives the cap fresh
//! from the tables ([`derive_lut_caps_bytes`]) and rebuilds `fp8_cache.bin` against
//! it in the same run (the two files must move together: the cached wrapper
//! circuits bake the cap). After any change to the LUT tables, the batch commitment
//! layout or the consensus `StarkConfig`, regenerate both with
//! `cargo run --release --no-default-features --bin build_cache src/api/fp8/fp8_cache.bin`
//! and commit them; the `lut_caps_file_matches_the_lut_tables` test pins the file.

use anyhow::{Result, ensure};
use plonky2::field::types::{Field, Field64, PrimeField64};
use plonky2::hash::hash_types::HashOut;
use plonky2::hash::merkle_tree::MerkleCap;
use plonky2::plonk::config::GenericConfig;
use plonky2::util::timing::TimingTree;

use super::zk::{C, D, F, Fp8Job, sample_dense_statement};
use crate::api::primitives::IncompleteBlockHeader;
use crate::circuit::fp8::driver::STARK_CAP_HEIGHT;

/// The Merkle cap type of the committed LUT oracle.
pub type LutCap = MerkleCap<F, <C as GenericConfig<D>>::Hasher>;

/// The committed caps file: one cap of [`LUT_CAP_LEN`] hashes, each four
/// little-endian `u64` field elements.
const LUT_CAPS_DATA: &[u8] = include_bytes!("lut_caps.bin");

pub(crate) const LUT_CAP_LEN: usize = 1 << STARK_CAP_HEIGHT;
const CAP_BYTES: usize = LUT_CAP_LEN * 4 * 8;

// A truncated or stale-geometry file fails the build, not verification.
const _: () = assert!(LUT_CAPS_DATA.len() == CAP_BYTES);

/// The LUT setup cap, parsed from the committed file.
pub fn committed_lut_cap() -> LutCap {
    cap_from_file_bytes(LUT_CAPS_DATA)
}

/// [`committed_lut_cap`] against explicit file bytes — build tooling, for reading a
/// freshly derived file before it is committed and embedded.
pub fn cap_from_file_bytes(bytes: &[u8]) -> LutCap {
    assert_eq!(bytes.len(), CAP_BYTES, "malformed LUT caps file ({} bytes)", bytes.len());
    MerkleCap(
        bytes
            .as_chunks::<32>()
            .0
            .iter()
            .map(|hash| HashOut {
                elements: std::array::from_fn(|i| {
                    let element = u64::from_le_bytes(hash[i * 8..][..8].try_into().unwrap());
                    assert!(element < F::ORDER, "non-canonical field element in the LUT caps file");
                    F::from_canonical_u64(element)
                }),
            })
            .collect(),
    )
}

/// Build tooling: derives the cap fresh from the LUT tables (one oracle build)
/// in the file's layout. `build_cache` writes the result as `lut_caps.bin` and
/// compiles `fp8_cache.bin`'s circuits against the same cap.
pub fn derive_lut_caps_bytes() -> Result<Vec<u8>> {
    let mut bytes = Vec::with_capacity(CAP_BYTES);
    // The cap is job-independent; the canonical statement only anchors batch
    // positions for the oracle build. The header never reaches the
    // preprocessed data, so pass the setup's explicit zero header rather
    // than the statement's (equally zeroed) ancestor header.
    let params = sample_dense_statement()?;
    let job = Fp8Job::derive(&params, &IncompleteBlockHeader::zero())?;
    let cap = job.system.preprocessed_data::<C>(&mut TimingTree::default()).cap();
    ensure!(
        cap.0.len() == LUT_CAP_LEN,
        "LUT cap height differs from the consensus StarkConfig"
    );
    for hash in &cap.0 {
        for element in hash.elements {
            bytes.extend_from_slice(&element.to_canonical_u64().to_le_bytes());
        }
    }
    Ok(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pins the committed `lut_caps.bin` to a fresh derivation from the LUT tables
    /// (~2 s: builds each family's oracle once). Fails after any change to the
    /// tables, the batch commitment layout or the consensus `StarkConfig` —
    /// regenerate the file (together with `fp8_cache.bin`) with
    /// `build_cache src/api/fp8/fp8_cache.bin`.
    #[test]
    fn lut_caps_file_matches_the_lut_tables() {
        let fresh = derive_lut_caps_bytes().expect("deriving the LUT caps from the tables");
        assert!(
            fresh == LUT_CAPS_DATA,
            "the committed lut_caps.bin drifted from the LUT tables; regenerate it (and fp8_cache.bin) with build_cache"
        );
    }
}
